#!/usr/bin/env ruby
require 'fileutils'

theme = ARGV[0] || ''
if theme[-3..-1] != ".py"
  STDERR.puts "Aborting - '#{theme}' does not appear to be a valid theme!"
  exit 1
end

basename = File.basename(theme)
site_packages = `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`.chomp
dest = File.join(site_packages, "/pygments/styles", basename)

FileUtils.rm(dest) if File.exist?(dest)
FileUtils.cp(theme, dest)
